### PR TITLE
unittests files

### PR DESCRIPTION
**Pull request by tricias260**
please help me review my unittests files. @SerryJohns @louiCoder @pktahinduka @ongwech . I await on your comments.

### CODE REVIEW

**Review by pktahinduka — COMMENTED** [review]
The code is well documented... Thumbs up.

**Comment by tricias260** [comment]
Thanks, Pete!

**Comment by ghost** [comment]
Neat UIs, and the project is well structured. 
This looks good to me.

**Comment by louicoder** [comment]
the tests look good and organised.

**Comment by tricias260** [comment]
Alright, this is encouraging ! Thanks

**Pull request merged**
